name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] Brief description of the feature"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature or improvement you would like to see.
      placeholder: "For example: Add an export data button..."
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How will this feature help users?
      placeholder: "For example: Allow users to save data locally..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following.
      options:
        - label: I have searched existing Issues and found no similar requests
          required: true
